sudo: false
language: nix

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script: 
  - stack --stack-yaml stack-nix.yaml --no-terminal --install-ghc --flag hlabyrinth:llvm test
  - stack --stack-yaml stack-nix.yaml install hlint
  - hlint .

cache:
  directories:
    - $HOME/.stack
