sudo: required
dist: trusty

env:
 - CABALVER=1.18 GHCVER=7.8.3
 - CABALVER=1.18 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=1.22 GHCVER=7.10.2
 - CABALVER=1.22 GHCVER=7.10.3
 - CABALVER=1.24 GHCVER=8.0.1
 - CABALVER=head GHCVER=head

matrix:
  allow_failures:
    - env: CABALVER=head GHCVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install -y cabal-install-$CABALVER ghc-$GHCVER happy-1.19.5 alex-3.1.7
 - travis_retry sudo apt-get install -y libgirepository1.0-dev libwebkitgtk-3.0-dev libwebkit2gtk-3.0-dev libpoppler-glib-dev libvte-2.90-dev libgtksourceview-3.0-dev libgstreamer1.0-dev
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install Cabal cabal-install
 - hash -r
 - cabal --version

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - pushd base
 - cabal install --dependencies-only
 - cabal configure
 - cabal build
 - cabal install
 - popd
 - cabal install --dependencies-only
 - cabal configure
 - cabal build
 # For building the test program later, doing it now avoids a recompilation
 - cabal run haskell-gi -- -l -O test Gtk Gdk
 - cabal run haskell-gi -- -c -O test Gtk
 - |
   if [ ${GHCVER%.*} = "7.8" ]; then
     echo Warning: No tests run since doctest does not install in GHC 7.8
   else
     cabal install --enable-tests --dependencies-only
     cabal test
   fi
 - cabal clean
 - cabal check
 - cabal sdist   # tests that a source-distribution can be generated

# Check that the resulting source distribution can be built & installed.
# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
# `cabal install --force-reinstalls dist/*-*.tar.gz`
 - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")

 - cd bindings
 - cabal sandbox init
 - cabal install --dependencies-only
 - cabal run genBuildInfo `./PKGS.sh`
 - cabal sandbox delete
 - cabal install -j3 ./GLib ./cairo ./Pango ./Gdk ./Gio ./GObject ./GdkPixbuf ./Atk
 - cabal install -j1 ./Gtk
 - cabal install -j3 ./GtkSource ./WebKit
 - cd ../test
 - cabal install --dependencies-only
 - cabal configure
 - cabal build
notifications:
  irc:
    channels: "irc.freenode.net#gtk2hs"
    skip_join: true
email: true
