sudo: false
dist: trusty
language: c

matrix:
  include:
    - ghc: "8.4.1"
      env:
        - CABALVER=2.2 GHCVER=8.4.1 
      addons:
        apt:
          sources:
            sourceline: ppa:hvr/ghc 
          packages: 
            - cabal-install-2.2
            - ghc-8.4.1

addons:
  apt:
    sources:
      - sourceline: ppa:hvr/ghc
    packages:
      - libsdl2-dev
      - happy-1.19.5 
      - alex-3.1.7 
      - libgirepository1.0-dev 
      - libgtk-3-dev
      - libcairo2-dev
      - libcairo-gobject2 

before_install:
 - mkdir -p ~/.local/bin
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$HOME/.local/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - travis_retry cabal update 
 - travis_retry cabal new-build all

cache:
 directories:
 - $HOME/.cabal/packages
 - $HOME/.cabal/store
 - $HOME/.cabal/bin

